tap "buo/cask-upgrade"
brew "mas"

tap "robotsandpencils/made"
brew "1password-cli"
# work
brew "mise"  # Version manager for neovim, node, python, ruby, etc.
brew "aria2"
brew "bat"
brew "cloc"
brew "eza"
brew "gnutls"
brew "gh"
brew "gnupg"
brew "jq"
brew "llvm"
brew "pinentry-mac"
brew "swiftlint"
brew "tree"
brew "wget"
brew "robotsandpencils/made/xcodes"
brew "git-delta"
brew "ffmpeg"
brew "fzf"
brew "tree-sitter"
brew "tree-sitter-cli"

cask "xcodes-app"
cask "visual-studio-code"
cask "keycastr"

# Mothers Ruin software
cask "apparency"
cask "suspicious-package"
cask "archaeology"

# fonts
cask "font-meslo-lg-nerd-font"
# quit apple music from opening
cask "overkill"

mas "BBEdit", id: 404009241
mas "Color Picker", id: 1545870783
mas "DaisyDisk", id: 411643860
mas "Developer", id: 640199958
mas "Front and Center", id: 1493996622
mas "Hush", id: 1544743900
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Magic Lasso", id: 1198047227
mas "Userscripts", id: 1463298887
mas "UTC Time", id: 1538245904
mas "Zavala", id: 1546457750

